//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18063
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VanLeeuwen.Projects.WebPortal.BusinessLogics.DataTransferService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="DataTransferService.IDataTransfer")]
    public interface IDataTransfer {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDataTransfer/SendFile", ReplyAction="http://tempuri.org/IDataTransfer/SendFileResponse")]
        VanLeeuwen.Projects.WebPortal.BusinessLogics.DataTransferService.SendFileResponse SendFile(VanLeeuwen.Projects.WebPortal.BusinessLogics.DataTransferService.SendFileRequest request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDataTransfer/SendFile", ReplyAction="http://tempuri.org/IDataTransfer/SendFileResponse")]
        System.Threading.Tasks.Task<VanLeeuwen.Projects.WebPortal.BusinessLogics.DataTransferService.SendFileResponse> SendFileAsync(VanLeeuwen.Projects.WebPortal.BusinessLogics.DataTransferService.SendFileRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDataTransfer/ReceiveFile", ReplyAction="http://tempuri.org/IDataTransfer/ReceiveFileResponse")]
        VanLeeuwen.Projects.WebPortal.BusinessLogics.DataTransferService.ReceiveFileResponse ReceiveFile(VanLeeuwen.Projects.WebPortal.BusinessLogics.DataTransferService.ReceiveFileRequest request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDataTransfer/ReceiveFile", ReplyAction="http://tempuri.org/IDataTransfer/ReceiveFileResponse")]
        System.Threading.Tasks.Task<VanLeeuwen.Projects.WebPortal.BusinessLogics.DataTransferService.ReceiveFileResponse> ReceiveFileAsync(VanLeeuwen.Projects.WebPortal.BusinessLogics.DataTransferService.ReceiveFileRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDataTransfer/DeleteFile", ReplyAction="http://tempuri.org/IDataTransfer/DeleteFileResponse")]
        bool DeleteFile(string fileName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDataTransfer/DeleteFile", ReplyAction="http://tempuri.org/IDataTransfer/DeleteFileResponse")]
        System.Threading.Tasks.Task<bool> DeleteFileAsync(string fileName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDataTransfer/Test", ReplyAction="http://tempuri.org/IDataTransfer/TestResponse")]
        string Test();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDataTransfer/Test", ReplyAction="http://tempuri.org/IDataTransfer/TestResponse")]
        System.Threading.Tasks.Task<string> TestAsync();
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SendFile", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class SendFileRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string databaseName;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public byte[] file;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public string fileName;
        
        public SendFileRequest() {
        }
        
        public SendFileRequest(string databaseName, byte[] file, string fileName) {
            this.databaseName = databaseName;
            this.file = file;
            this.fileName = fileName;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SendFileResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class SendFileResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public bool SendFileResult;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string errorMessage;
        
        public SendFileResponse() {
        }
        
        public SendFileResponse(bool SendFileResult, string errorMessage) {
            this.SendFileResult = SendFileResult;
            this.errorMessage = errorMessage;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ReceiveFile", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class ReceiveFileRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string databaseName;
        
        public ReceiveFileRequest() {
        }
        
        public ReceiveFileRequest(string databaseName) {
            this.databaseName = databaseName;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ReceiveFileResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class ReceiveFileResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public bool ReceiveFileResult;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string fileName;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public byte[] fileContent;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=3)]
        public string errorMessage;
        
        public ReceiveFileResponse() {
        }
        
        public ReceiveFileResponse(bool ReceiveFileResult, string fileName, byte[] fileContent, string errorMessage) {
            this.ReceiveFileResult = ReceiveFileResult;
            this.fileName = fileName;
            this.fileContent = fileContent;
            this.errorMessage = errorMessage;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IDataTransferChannel : VanLeeuwen.Projects.WebPortal.BusinessLogics.DataTransferService.IDataTransfer, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class DataTransferClient : System.ServiceModel.ClientBase<VanLeeuwen.Projects.WebPortal.BusinessLogics.DataTransferService.IDataTransfer>, VanLeeuwen.Projects.WebPortal.BusinessLogics.DataTransferService.IDataTransfer {
        
        public DataTransferClient() {
        }
        
        public DataTransferClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public DataTransferClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DataTransferClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DataTransferClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        VanLeeuwen.Projects.WebPortal.BusinessLogics.DataTransferService.SendFileResponse VanLeeuwen.Projects.WebPortal.BusinessLogics.DataTransferService.IDataTransfer.SendFile(VanLeeuwen.Projects.WebPortal.BusinessLogics.DataTransferService.SendFileRequest request) {
            return base.Channel.SendFile(request);
        }
        
        public bool SendFile(string databaseName, byte[] file, string fileName, out string errorMessage) {
            VanLeeuwen.Projects.WebPortal.BusinessLogics.DataTransferService.SendFileRequest inValue = new VanLeeuwen.Projects.WebPortal.BusinessLogics.DataTransferService.SendFileRequest();
            inValue.databaseName = databaseName;
            inValue.file = file;
            inValue.fileName = fileName;
            VanLeeuwen.Projects.WebPortal.BusinessLogics.DataTransferService.SendFileResponse retVal = ((VanLeeuwen.Projects.WebPortal.BusinessLogics.DataTransferService.IDataTransfer)(this)).SendFile(inValue);
            errorMessage = retVal.errorMessage;
            return retVal.SendFileResult;
        }
        
        public System.Threading.Tasks.Task<VanLeeuwen.Projects.WebPortal.BusinessLogics.DataTransferService.SendFileResponse> SendFileAsync(VanLeeuwen.Projects.WebPortal.BusinessLogics.DataTransferService.SendFileRequest request) {
            return base.Channel.SendFileAsync(request);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        VanLeeuwen.Projects.WebPortal.BusinessLogics.DataTransferService.ReceiveFileResponse VanLeeuwen.Projects.WebPortal.BusinessLogics.DataTransferService.IDataTransfer.ReceiveFile(VanLeeuwen.Projects.WebPortal.BusinessLogics.DataTransferService.ReceiveFileRequest request) {
            return base.Channel.ReceiveFile(request);
        }
        
        public bool ReceiveFile(string databaseName, out string fileName, out byte[] fileContent, out string errorMessage) {
            VanLeeuwen.Projects.WebPortal.BusinessLogics.DataTransferService.ReceiveFileRequest inValue = new VanLeeuwen.Projects.WebPortal.BusinessLogics.DataTransferService.ReceiveFileRequest();
            inValue.databaseName = databaseName;
            VanLeeuwen.Projects.WebPortal.BusinessLogics.DataTransferService.ReceiveFileResponse retVal = ((VanLeeuwen.Projects.WebPortal.BusinessLogics.DataTransferService.IDataTransfer)(this)).ReceiveFile(inValue);
            fileName = retVal.fileName;
            fileContent = retVal.fileContent;
            errorMessage = retVal.errorMessage;
            return retVal.ReceiveFileResult;
        }
        
        public System.Threading.Tasks.Task<VanLeeuwen.Projects.WebPortal.BusinessLogics.DataTransferService.ReceiveFileResponse> ReceiveFileAsync(VanLeeuwen.Projects.WebPortal.BusinessLogics.DataTransferService.ReceiveFileRequest request) {
            return base.Channel.ReceiveFileAsync(request);
        }
        
        public bool DeleteFile(string fileName) {
            return base.Channel.DeleteFile(fileName);
        }
        
        public System.Threading.Tasks.Task<bool> DeleteFileAsync(string fileName) {
            return base.Channel.DeleteFileAsync(fileName);
        }
        
        public string Test() {
            return base.Channel.Test();
        }
        
        public System.Threading.Tasks.Task<string> TestAsync() {
            return base.Channel.TestAsync();
        }
    }
}
